[package]
name = "hypewwisoww"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "hypewwisoww"

[[bin]]
name = "hypewwisoww"
path = "src/main.rs"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"

